<a href="https://colab.research.google.com/github/pixtrxk/data_science/blob/main/lin_algebr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
v1 = np.array([1,5])

In [3]:
np.linalg.norm(v1)

5.0990195135927845

In [4]:
v2 = np.array([-1,3,6])
np.linalg.norm(v2)

6.782329983125268

In [5]:
v1 = np.array([1,3])
v2 = np.array([4,6])
np.linalg.norm(v1-v2)

4.242640687119285

In [6]:
x = np.array([[1,2],[3,4]])
y=np.array([[2],[3]])
print(x, '\n')
print(y)
x.dot(y)


[[1 2]
 [3 4]] 

[[2]
 [3]]


array([[ 8],
       [18]])

In [4]:
X=np.array([[1,3],[2,5]])
print(X)
np.linalg.det(X)


[[1 3]
 [2 5]]


-1.0

In [6]:
np.eye(4, dtype='int')


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [13]:
A = np.array([[2,4],[-1,3]])
B = np.linalg.inv(A)
# print(A,type='int')
print(B)



[[ 0.3 -0.4]
 [ 0.1  0.2]]


In [26]:
np.set_printoptions(precision=6, suppress=True)
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [27]:
A

array([[ 2,  4],
       [-1,  3]])

In [28]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [5]:
A = np.array([[3,6],[1,1]])
B = np.array([[12],[5]])
print(A, '\n')
print(B)

[[3 6]
 [1 1]] 

[[12]
 [ 5]]


In [7]:
invv = np.linalg.inv(A)
np.dot(invv,B)


array([[ 6.],
       [-1.]])

In [9]:
np.set_printoptions(precision=6, suppress=True)
print(invv)

[[-0.333333  2.      ]
 [ 0.333333 -1.      ]]


In [6]:
P = np.array([[12,111,135,65],[33,5,88,987],[22,43,44,7]])
P

array([[ 12, 111, 135,  65],
       [ 33,   5,  88, 987],
       [ 22,  43,  44,   7]])

In [9]:
np.sum(P,axis=1)

array([ 323, 1113,  116])