<a href="https://colab.research.google.com/github/pixtrxk/data_science/blob/main/basic/np_basic_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
np.__version__

'1.23.5'

In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [77]:
x = np.array([[1,2],[3,4],[4,5]])
x.ndim
x.shape

(3, 2)

In [18]:
x = np.array(
    [[[1,2,3],[3,4,5]],
     [[4,5,6],[5,7,8]]]
    )
x.shape

(2, 2, 3)

In [22]:
A = np.array([[1,2,3],[4,5,6]], dtype = 'int8')
A.dtype
print(A)

[[1 2 3]
 [4 5 6]]


In [25]:
np.zeros(shape=(8,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
np.full(shape=(3,4), fill_value=5, dtype='int')

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [30]:
A = np.arange(10)
B = np.arange(start=10,stop=50,step=5)
print(A)
print(B)

[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25 30 35 40 45]


In [32]:
C = np.linspace(start=1,stop=5,num=6)
print(C)

[1.  1.8 2.6 3.4 4.2 5. ]


In [44]:
A = np.arange(18)
A.reshape(-1,3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [51]:
A = np.array([3,5,7])
B = np.array([2,3,4])
A*B

array([ 6, 15, 28])

In [56]:
X = np.array([[2,3],[5,7]])
Y = np.array([[1,9],[3,6]])
print(X, '\n')
print(Y)

[[2 3]
 [5 7]] 

[[1 9]
 [3 6]]


In [55]:
X*Y


array([[ 2, 27],
       [15, 42]])

In [58]:
np.dot(X,Y)

array([[11, 36],
       [26, 87]])

In [60]:
X @ Y

array([[11, 36],
       [26, 87]])

In [63]:
np.random.randn(10,3)

array([[ 0.35666137,  0.39575966,  1.54601928],
       [ 0.57484539, -1.02219234,  0.79201294],
       [-0.02077257, -0.22498146,  0.32739671],
       [-0.75054749,  0.87985559, -1.22957972],
       [-0.76689863,  0.28939457,  0.78528209],
       [-0.6187872 , -0.05537352,  0.13747908],
       [ 0.56758588,  2.33714125,  1.01218863],
       [-1.63808493, -0.87929505,  0.93762446],
       [-1.23559128,  0.26962273, -0.32169095],
       [-0.92719468,  0.46297424,  1.14500652]])

In [64]:
np.random.rand(10,3)

array([[0.7550435 , 0.50488716, 0.34385538],
       [0.67329416, 0.10047157, 0.44131318],
       [0.02213452, 0.97613783, 0.52519261],
       [0.44654188, 0.30956861, 0.84886279],
       [0.13807674, 0.07500462, 0.05764182],
       [0.90405819, 0.13018062, 0.05178594],
       [0.02997833, 0.90175702, 0.96418147],
       [0.42985223, 0.51431055, 0.75528177],
       [0.1679262 , 0.68576107, 0.57242756],
       [0.10603007, 0.76565609, 0.4325779 ]])

In [75]:
np.random.randint(low=3,high=15,size=(2,3))

array([[13, 12,  9],
       [12,  5, 10]])

In [79]:
np.sqrt(9)

3.0

In [7]:
np.linspace(start=10,stop=13,num=6)
np.arange(start=10,stop=14,step=1)


array([10, 11, 12, 13])

In [12]:
np.all(np.arange(start=0,stop=14,step=1))

False

In [14]:
A=np.random.rand(5)
print(A)


[0.28640579 0.61454656 0.92931676 0.34784089 0.76934169]


In [15]:
np.argmax(A)

2

In [18]:
print(A[np.argsort(A)])

[0.28640579 0.34784089 0.61454656 0.76934169 0.92931676]


In [23]:
A = np.arange(20)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [30]:
A = A.reshape(4,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [38]:
A[2:4,4]

array([14, 19])

In [52]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [54]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [61]:
A = np.arange(start=-10,stop=10,step=.5)
A = A.reshape(10,-1)
print(A)


[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]
 [  0.    0.5   1.    1.5]
 [  2.    2.5   3.    3.5]
 [  4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5]
 [  8.    8.5   9.    9.5]]


In [78]:
A[np.bitwise_and(A > 0,A < 7)]


array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])